# Generated by Django 4.2.2 on 2023-06-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade_point',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='choice', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='question', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
